name: Build VST3 Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install CMake
      uses: lukka/get-cmake@v3.27.0

    - name: Clone JUCE
      run: git clone --depth 1 https://github.com/juce-framework/JUCE.git

    - name: Configure
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Upload VST3 Artifact
      uses: actions/upload-artifact@v3
      with:
        name: EltraV1-VST3
        path: build/Release/*.vst3
