name: Build VST3 Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install CMake
        uses: lukka/get-cmake@v3.29.2

      - name: Configure Project with CMake
        run: cmake -B build -S . -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=OFF -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload VST3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Eltrav1-VST3
          path: build/**/Eltrav1.vst3
